"""sync ORM definitions with DB schema

Revision ID: fa33e2cd9dda
Revises: 006
Create Date: 2026-03-02 09:21:03.401751
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa33e2cd9dda'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depth_plans',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_spec_id', sa.Uuid(), nullable=True),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('degraded_steps', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('step_errors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_depth_plans_workspace_id'), 'depth_plans', ['workspace_id'], unique=False)
    op.create_table('depth_artifacts',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('disclosure_tier', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['depth_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('plan_id', 'step', name='uq_depth_artifact_plan_step')
    )
    op.create_index(op.f('ix_depth_artifacts_plan_id'), 'depth_artifacts', ['plan_id'], unique=False)
    op.alter_column('assumption_library_entries', 'justification',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('assumption_library_entries', 'source',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('assumption_library_entries', 'evidence_refs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('assumption_library_versions', 'entry_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('line_items', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('mapping_library_entries', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('mapping_library_versions', 'entry_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('override_pairs', 'project_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('run_quality_summaries', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('scenario_patterns', 'sector_focus',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'typical_shock_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'typical_assumptions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'recommended_sensitivities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'recommended_contrarian_angles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'source_engagement_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=False)
    op.alter_column('workspaces', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('scenario_patterns', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'source_engagement_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'recommended_contrarian_angles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'recommended_sensitivities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'typical_assumptions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'typical_shock_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'sector_focus',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenario_patterns', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('run_quality_summaries', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('override_pairs', 'project_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('mapping_library_versions', 'entry_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('mapping_library_entries', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('line_items', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('assumption_library_versions', 'entry_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('assumption_library_entries', 'evidence_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('assumption_library_entries', 'source',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('assumption_library_entries', 'justification',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_depth_artifacts_plan_id'), table_name='depth_artifacts')
    op.drop_table('depth_artifacts')
    op.drop_index(op.f('ix_depth_plans_workspace_id'), table_name='depth_plans')
    op.drop_table('depth_plans')
    # ### end Alembic commands ###
